### ISSUE TITLE
On selecting a soundset, nothing happens.

### ISSUE THREAD

**Issue by jonleb** [frondeus/fvtt-syrin-control#38] opened 2022-06-01 06:46 UTC
All soundsets are shown but when I select one, it come back to --no soundsets--

**Steps to reporoduce**

1. Go to Music
2. Select soundsets dropdown menu 
3. Click on one of them

Result: soundsets come back to --no soundsets--

1. go to folder in the toolbar to select a macro
2. Macro list is open

Result: no sounds are available

**Configuration**
MacOS Monterey 12.3.1 on MacBook Air M1
Google Chrome Version 101.0.4951.64 (Build officiel) (arm64)
FoundryVTT: V9 build 269
Syrin-control: 0.3.0
Server is install on my local machine 

**Screenshots**
![image](https://user-images.githubusercontent.com/728007/171343865-6b345cb8-2052-4633-8a5c-e6ff1b08d497.png)
![image](https://user-images.githubusercontent.com/728007/171343918-663c66dd-0d25-4cf1-ad69-d7fa7d83f5b7.png)
![image](https://user-images.githubusercontent.com/728007/171343967-e584bc5e-aa73-4aa4-98f9-abd5e762f728.png)

**Logs**
Reload Foundry, the
[FoundryVTT-SyrinControl.log](https://github.com/frondeus/fvtt-syrin-control/files/8811642/FoundryVTT-SyrinControl.log)

**Comment by RyanD** [comment] 2022-06-14 20:23
I think this is a duplicate of #35

**Comment by jonleb** [comment] 2022-06-22 06:19
> I think this is a duplicate of #35

Indeed.

**Comment by frondeus** [comment] 2022-08-08 20:46
I am going to close this one in favor of #35 so if you have any questions regarding to this please don't hesitate and write a mail to me or just comment under #35.

**Closed by frondeus** 2022-08-08 20:46 UTC
Labels: bug
