### ISSUE TITLE
a player is no earing sound "lacks permission error"

### ISSUE THREAD

**Issue by Tackian** [frondeus/fvtt-syrin-control#75] opened 2023-02-21 07:00 UTC
**Describe the bug**

One of my player just don't ear the syrinscape sound but is earing well the regular playlist sound

**Logs**
this is the log from te Forge

"2023-02-20 16:20:12 [error] User benoit12 lacks permission to update Playlist [XXXXXXXX (my API]
Error: User benoit12 lacks permission to update Playlist [XXXXXXX (my API]
at ServerDatabaseBackend._updateDocuments (file:///opt/foundryvtt/dist/database/backend/server-backend.mjs:1:3830)
at async Semaphore._try (file:///opt/foundryvtt/common/utils/semaphore.mjs:101:17)"

**Comment by frondeus** [comment] 2023-02-21 08:01
Duplicate of #74

**Comment by Tackian** [comment] 2023-02-21 08:05
argh sorry !

**Closed** 2023-02-21 08:05 UTC
Labels: bug
