### ISSUE TITLE
Firefox works, chrome and edge do not. 

### ISSUE THREAD

**Issue by YenBenGrey** [frondeus/fvtt-syrin-control#42] opened 2022-08-07 08:58 UTC
**Describe the bug**
 very similar to previous bugs, when clicking on the playlist drop down menu I can see all the playlists or sound sets but when I choose one the moods button greys out and the playlist drop down resets. This is in chrome and edge. 

In Firefox it works perfectly. 

**To Reproduce**
 resets to no sound set chosen, moods drop down goes grey. 

**Expected behavior**
 soundset should be chosen, then mood, and it should play in Syrinscape online player. (It works in Firefox) 

**Screenshots**

**Details**

**Logs**

```
Paste logs here.
```

**Additional context**

**Comment by YenBenGrey** [comment] 2022-08-08 18:57
Additionally when I set up all the sounds using foundry in Firefox when I go back to chrome they’re all there and working. I just can’t edit it in chrome.

**Comment by frondeus** [comment] 2022-08-08 20:21
That sounds like duplicate of #35 

The problem is, I cannot replicate it :( I just made another empty world with SyrinControl, added my Auth token, waited maybe 5s and soundsets were populated. On chrome.

**Comment by YenBenGrey** [comment] 2022-08-08 20:32
Sorry, it is a duplicate of #35 but I forgot to add that I can use it no problem in Firefox. 

Could it be that I’m using an iMac? 

Garry Miller
07916320866

**Comment by frondeus** [comment] 2022-08-08 20:46
I am going to close this one in favor of #35 so if you have any questions regarding to this please don't hesitate and write a mail to me or just comment under #35.

**Closed by frondeus** 2022-08-08 20:46 UTC
Labels: bug
