### ISSUE TITLE
Soundsets all there, no failure messages, but no sound

### ISSUE THREAD

**Issue by Valle1505** [frondeus/fvtt-syrin-control#40] opened 2022-06-22 13:27 UTC
**Describe the bug**

I can see the soundsets and all the elements. I can add a mood to a scene without trouble, but the actual sound is missing. Syrinscape player is open and works fine if I play the sound from that directly (Volume is up both in foundry and on the computer).
**To Reproduce**
No steps, just do what you would normally do if this worked, but with no sound playing.

**Expected behavior**

I expected the mood to play when I enter the scene. A message shows up that the mood is now playing, but no sound.
**Screenshots**

**Details**

**Logs**

```
Paste logs here.
```

**Additional context**

**Comment by Valle1505** [comment] 2022-06-22 14:06
Why would I need that to use it at home on my own computer? I dont play online. As I mentioned in the first post, I have syrinscape player open and working fine. That is paid for and no use for you to provide any sounds whatsoever.

**Comment by frondeus** [comment] 2022-06-22 16:42
First of all, sorry it is not my best day. I misunderstood the issue. Also, clearly, I'm missing not only social but also reading and understanding skills today.


What you say is, that even though my plugin says that it did successfully send a request to the Syrinscape API, the player does not receive a new mood. 

That is definitely weird. I see that you, unfortunately, didn't provide extra details, especially which browser you are using, and what is the version of Foundry.  

Do you see any errors in browser console logs? Since I cannot reproduce the error I need these to actually work on the issue.

 Or is there an error in the network tab (usually you can see requests when you press F12 and then open the Network tab) when you change the active scene? Are one-shot elements playing just fine and only moods are misbehaving?

Also please keep in mind that this is my personal pet project and not the official product. I am not sponsored by anyone and I do not have a Patreon page, therefore I don't fully understand your last sentence. I hope you were not scammed.

Again, sorry for my rushed reactionh

**Comment by Valle1505** [comment] 2022-06-23 19:19
Ok… Lets just put it behind us then.

I am sorry that I didnt provide the info you need. The problem is that everything Works as it should according to the program. It says that it loads the mood when I enter a new scene with a supposed mood connected, and the mood seems like its playing as you can see on the Picture. But no sound. There is however some error messages when I press F12 that I dont understand[](url
![Skærmbillede (33)](https://user-images.githubusercontent.com/108005639/175380132-0d811eda-b2e1-4f52-8254-5dd4258a8560.png)
)

**Comment by Valle1505** [comment] 2022-06-23 21:34
Just to make it perfectly clear... This is for local use only over my wifi. Syrinscape is downloaded, paid for and working when used directly from their player.. The mood says its playing when I activate a scene, but it doesnt

**Comment by frondeus** [comment] 2022-08-08 21:06
On a Network page, is Foundry sending requests to Syrinscape API when you are commanding it to change the mood?
Also sorry for the delay, finally got time to develop this module.

**Comment by Valle1505** [comment] 2022-08-09 14:49
No, but first I should explain… I have a gaming dungeon with a table with TV in it, surround system and so on, so we always play in person never online, so what I wanted was a system for me to change syrinscape moods from within foundry, but what was confusing was that I own syrinscape, and can use it with no problems, but it doesn’t Work with syrin control on its own. I fixed it though, because it Works when I run onlineplayer. It isnt optimal, but at least it Works.

I hope, it will someday Work with just syrinscape, since it uses more memory on my PC to have both that and syrinscape open, and I cant use my surround using onlineplayer.

Also, I dont know if this is something you have considered, but putting syrinscape links in journal or on map would be amazing. For instance CoS have so many different sounds, but you can only connect one mood to the map, if you want another, you have to go into syrinscape anyway.

Regards

Martin Bomark

Sendt fra Mail<https://go.microsoft.com/fwlink/?LinkId=550986> til Windows

Fra: Wojciech ***@***.***>
Sendt: 8. august 2022 22:06
Til: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Emne: Re: [frondeus/fvtt-syrin-control] Soundsets all there, no failure messages, but no sound (Issue #40)


On a Network page, is Foundry sending requests to Syrinscape API when you are commanding it to change the mood?
Also sorry for the delay, finally got time to develop this module.

**Comment by frondeus** [comment] 2022-08-10 13:15
Oh, so just to be clear, you were using the Syrinscape app (the one where you can select moods, play one-shots etc.) , not the online player, and it didn't react to the changing mood.
But when you use the Syrinscape Online app (the one which is a 100% read-only, passive app, where you cannot change the mood), then does the sound changes correctly?

**Comment by Valle1505** [comment] 2022-08-11 16:09
Precisely

Sendt fra Mail<https://go.microsoft.com/fwlink/?LinkId=550986> til Windows

Fra: Wojciech ***@***.***>
Sendt: 10. august 2022 14:15
Til: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Emne: Re: [frondeus/fvtt-syrin-control] Soundsets all there, no failure messages, but no sound (Issue #40)


Oh, so just to be clear, you were using the Syrinscape app (the one where you can select moods, play one-shots etc.) , not the online player, and it didn't react to the changing mood.
But when you use the Syrinscape Online app (the one which is a 100% read-only, passive app, where you cannot change the mood), then does the sound changes correctly?

**Comment by frondeus** [comment] 2022-08-11 16:16
In that case, I need to close the issue.
That is a problem on the Syrinscape API side, not something on my module. I would recommend writing to the Syrinscape team on their forum. They tend to respond in a couple of hours.

Meanwhile about your suggestion:

> Also, I dont know if this is something you have considered, but putting syrinscape links in journal or on map would be amazing. For instance CoS have so many different sounds, but you can only connect one mood to the map, if you want another, you have to go into syrinscape anyway.

Well, I'm not sure about journal, but I just released a pre-release of new version that adds support for mood macros!
https://github.com/frondeus/fvtt-syrin-control/releases/download/0.4.0-alpha-1/module.json

That could help you with changing the moods on the fly. You can store the macros in macro folders or even in compendia.
I bet there is also a module that allows you to play macros from the journal notes.

If you have more questions, please let me know, either by mail or by opening a discussion/new issue.

**Closed by frondeus** 2022-08-11 16:16 UTC
Labels: bug

**Comment by Valle1505** [comment] 2022-08-11 17:55
Thank you, that if I can make macros for the moods I can just put them into the journal, which makes it much easier since I can just click them as I read through the journal for my players.

Sendt fra Mail<https://go.microsoft.com/fwlink/?LinkId=550986> til Windows

Fra: Wojciech ***@***.***>
Sendt: 11. august 2022 17:16
Til: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Emne: Re: [frondeus/fvtt-syrin-control] Soundsets all there, no failure messages, but no sound (Issue #40)


In that case, I need to close the issue.
That is a problem on the Syrinscape API side, not something on my module. I would recommend writing to the Syrinscape team on their forum. They tend to respond in a couple of hours.

Meanwhile about your suggestion:

Also, I dont know if this is something you have considered, but putting syrinscape links in journal or on map would be amazing. For instance CoS have so many different sounds, but you can only connect one mood to the map, if you want another, you have to go into syrinscape anyway.

Well, I'm not sure about journal, but I just released a pre-release of new version that adds support for mood macros!
https://github.com/frondeus/fvtt-syrin-control/releases/download/0.4.0-alpha-1/module.json<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffrondeus%2Ffvtt-syrin-control%2Freleases%2Fdownload%2F0.4.0-alpha-1%2Fmodule.json&data=05%7C01%7C%7C1b4a8cdb026b44fa57ed08da7bb4ea0f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637958314188232288%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=zXsrEn%2BiGRmmJXWnjuuABzXxF6%2Bpm%2FP3JHWTAlxJnIg%3D&reserved=0>

That could help you with changing the moods on the fly. You can store the macros in macro folders or even in compendia.
I bet there is also a module that allows you to play macros from the journal notes.

If you have more questions, please let me know, either by mail or by opening a discussion/new issue.

**Comment by Valle1505** [comment] 2022-10-11 07:39
Ok… Lets just put it behind us then.

I am sorry that I didnt provide the info you need. The problem is that everything Works as it should according to the program. It says that it loads the mood when I enter a new scene with a supposed mood connected, and the mood seems like its playing as you can see on the Picture. But no sound. There is however some error messages when I press F12 that I dont ***@***.***

Sendt fra Mail<https://go.microsoft.com/fwlink/?LinkId=550986> til Windows

Fra: Wojciech ***@***.***>
Sendt: 22. juni 2022 17:42
Til: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Emne: Re: [frondeus/fvtt-syrin-control] Soundsets all there, no failure messages, but no sound (Issue #40)


First of all, sorry it is not my best day. I misunderstood the issue. Also, clearly, I'm missing not only social but also reading and understanding skills today.

What you say is, that even though my plugin says that it did successfully send a request to the Syrinscape API, the player does not receive a new mood.

That is definitely weird. I see that you, unfortunately, didn't provide extra details, especially which browser you are using, and what is the version of Foundry.

Do you see any errors in browser console logs? Since I cannot reproduce the error I need these to actually work on the issue.

Or is there an error in the network tab (usually you can see requests when you press F12 and then open the Network tab) when you change the active scene? Are one-shot elements playing just fine and only moods are misbehaving?

Also please keep in mind that this is my personal pet project and not the official product. I am not sponsored by anyone and I do not have a Patreon page, therefore I don't fully understand your last sentence. I hope you were not scammed.

Again, sorry for my rushed reactionh
